apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vgq0ic2wQzsVZotZrohdhsOMujw/MYIcG+5zpya+/EnOwGsUfsw1ad24hDCZRCpBNBnH/hJuryLZDVDGKqpNq2Kq1mzzshNOtTZDZCtVMg1HKtK4iqlWkiq6tNjxW87SJ6kh7lMbtJwzfHKch8gt7OcDgLCGz1hTCIlKVKgXZN7OunCceEp7F/Frr5wniZ5bUt9mbv/mMQVYSlU1JeEiyXvhRhDfm6K+XMjKavjZCkFve4EGavXoDGKpXGp3U3a98lD2QuUBlgvIw2LqEAMRjmxDWw3AwlejhPHhWCD8W3LghbzWIDx1TX7QU03qhF9G7x0Qc8VxSWAsiZgH/mDbqcFhIWXEWAnFLLsAEy+jQegUhey7gKZ96X8FqobeQnu6,iv:DoivvhSZ6DkHknJQLdedeBisv/omII8QsUeiL1Y1/QM=,tag:v2WTr+9PVitHZx0ywi7OOQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:TUXH89DaFGoGhk9nFCmHGXpn4KK8neRHdwMoXYj8v8F7V3TAKLWtrlfp9UAd9MrgqfGY1u8R/wt7GDne7WFWBtAVixUa6eF7i6/NJr873utFFIbOAdRT5bn+CF/eBgU05GvKUr5rdDRcg82HMYTC/hmKRkdlbp4mf6YWOYiWQsnv3skkda0zbOEfJnKEYzKQhTUbv9tYJkuiY3fx0kMydHKOv8Bb2geNAv7+q7Dm5jBoYbGKD7SspOQyDQPFrxMqyEMDW3bBqT5UthNMrA==,iv:QeyJ3Js5eai7hYAUCgVou8VdoMe5QuO7HV9pHKV+O6U=,tag:S+Hm2VN+02EWjQGFQO6+3w==,type:str]
    known_hosts: ENC[AES256_GCM,data:/E4xmFWyWCfkRiIZgasndrafxpj/rTVE9VyVsR/vOwVq2o4gip/j+zsgy/oaZdg2422zBcJeb9E/LHrEhCdNmXe4faHagT7iPcTXJEE2ZUHYzIXmhsqwPCc07b+1klCoUFeuU5vt+OtIr86GqazJKzcM7VrVhSJYtJSMOc0SI/35xvUnRepLovQ0EG3ETjiuIGkcd/M9zey4rwvkG/4+Sn5978BfeIZ6VAqb,iv:Sqy5pzI3d5quRlGaExxPa3pI4rU5F1dU2qwtKmkjeJ8=,tag:2dPt9Q77X1hs0e8uQyDsMg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ehy7jh8y4rv03t6uv00kfx9afzw4nvx3zxd4z78kxsnu24gv592sps54vg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOVJSZGIzaFNJV3Vyc3VT
            MTgwcC8vWXEzRmZkdU16dFMvYzVXNkJVMWhnCkJXTlduZzBDRFpmUVdHaUdUVUlI
            ckErMnVCZURqRTRVbTAwZjAxeDJwOTAKLS0tICtWaUMrN3A5dGdoSFBGaVVqeWJQ
            U2puSGZXanJDd29pUzlCNU83NmJmZXMKVo2mvHL1YJ6/fbJnNUVT+l0SO7JiS+Ci
            kMneR4WbD7qcz9Yb4s/u3dYJ2Tf/b6DMV5SEH08ZeaV7Yaf1ZzFv2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-27T00:18:34Z"
    mac: ENC[AES256_GCM,data:xF+UOis3ZYye2i1EknILGLdHZf5q977FHSKQJ1QZQnfvnmUAlEgwaiPNlv5D7p129N1XBWf8OlozFM013WwuuBWsRp+rR2bxqMQN9SaRHheXz58dWyEJZr4AHwyHuaUbbLVdwlFFqDaS2x9kS4I5SRf/pSLlZYs3pXG9OvljYZQ=,iv:1A0KmM+WD6DNe6E0fzOrtFK28YmimZ9Si62avSbvFA4=,tag:vOD+gsYPRhIAdkw62QNK1w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
