apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Z6A9xpTXOH8Skp3B8xeLAvOoryu0RLHOUyqlNxUHLFh9Yxh5OHqjLQlI012H9NspvAy4XWA3Rr05JV0NOYZ40fCU9XhxfvTBKNBGXJCbD+hvgsOR7funxstceco/gLFVduema4LM+BmtxdrWzHtw6IG6BDv2JytFD+t1SmbKdchz6TV4RCUqrPXj+d3pLNWuKzYTgIJRxTwl9RQzKvFIutYnjcMTY5xNbZYtfr4+ik94rf0X2o1OihRSmRzz4QRf/O0ZvPueP9on4WNkZK1c5enNG1k+f7rYT4WsVmOVMxxTsA+y9eU5UZQjfg3ae3f6RtkbnJmIEaY94MGwy+O+YfSp/lQtPFt5Dd8JPydsN9HkSWBD3g+FRdrGOaNCXaoX,iv:3koWSQ/o+h3fUfufTCSNImWSfVvi90bwxR/M5xHTLq8=,tag:A2ncAH4u6vZAMFLl++pihg==,type:str]
    identity.pub: ENC[AES256_GCM,data:DrVuSdEhC3EurELU5CmeivcbHGNbkkmyV7x6dAryT15jiFv7uNFtMcNTiPihgX+DtFEfBSdWvECp8QtZXLC2lMNsI8epz4S60K3S40UL6FgyzTo8TPE7VpP1T+cKJA0ZMboVj4DLfumwc88RFXMEnGpfV9K0/f6Tie7gtonCFVnZALKVtSNHOPS+xxcdp+n4VunAE8/skTspR4n4g9fwx3wtkjLL6cMqm5Rz0GaxOEQeKZZ55Z9HB1Ca8Xo6jZE20TSvsV77EE6sNJVbcQ==,iv:3+JRdDj+xkn/PoBGGwo3vegtd3dYN5bsVaksIO2ZSZU=,tag:h6GAWSneuWqUW4n95J11bA==,type:str]
    known_hosts: ENC[AES256_GCM,data:5M+Fqihu47ylka0qplPpcKGgW9AvFORWIaMO+zHduR42FeCWQTlMqH4mip98vSvcsM/qln7X6V5w86WA/4aTMqA9XPdEgDKwVJFh/dc6Qwgmnsn0sfQoeEhETqWci5ra0IVK/PNSblfMyQdi26tErdta5MVkLRfog8GWfaMJS14zg0HXKr3JV+qQ8Kr56zK+Q3b8SmATiw4VLC2c2ugte01Vbe60pGiZdSfm,iv:KBhGURWI6a+OgbWg2dd6rl7KHyUV+FYpMPiQHt8crFs=,tag:r6VTz5rE/olSsUhqjJFIVA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ehy7jh8y4rv03t6uv00kfx9afzw4nvx3zxd4z78kxsnu24gv592sps54vg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUUhhbUZkN1RLc0p5eDY2
            eEtqQTBVbHJlVFhmcm8wZjhnWk8vaURSdno4CmJrY0FnZ3ZWb1NnRVI5VHIyZFBY
            ejAxR3lkK2NxWjU5RVUrU2UrTk9NcU0KLS0tIGRKSVgxSmNVRVQ2MnljZlZqTjNt
            UHYzdE5GQm9KamJqcmhHWGNqVzIzVnMKySZ7r3hDZnuPeEmJQAalnDeDoxL6EklD
            EQz4DJqrDMMzWLJ7bG2X7VGV/wW14ejU6ZwTcttFGXAsqhet2HrEXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T23:39:32Z"
    mac: ENC[AES256_GCM,data:kqzgN+UIKwmwfmaE48ybJO2ZJyROjDyBdJiZq1PRRhJ1Wy5Btezwpv2yxB0N9UUw3q3LHVrX7Yefs3saBRH+cvzBglNY1YT9TA6rxbh/nXF7a1CF12Bda9BX/rl4GQSQzVDzi78W/f7LFyVQWnROLqpJXL1hJTio2gaVrYLlcjc=,iv:n13Py7fpqyEOTsep3XmAMh93j2kzrE0GJxRTohDRiAA=,tag:ENsUuk8F8Zys2J0ejv7z9A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
