---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: sonarr
      version: 24.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
    - name: volsync
      namespace: volsync
  values:
    TZ: Australia/Melbourne
    credentials:
      s3:
        type: s3
        url: "${S3_URL}"
        bucket: "${S3_PREFIX}-sonarr"
        accessKey: "${S3_ID}"
        secretKey: "${S3_KEY}"
        encrKey: "${S3_ENC_KEY}"
    workload:
      exportarr:
        enabled: false
    metrics:
      main:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: sonarr.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: false
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            cleanupTempPVC: false
            cleanupCachePVC: false
            dest:
              enabled: true
              cacheCapacity: 10Gi
            src:
              enabled: true
              cacheCapacity: 10Gi
              trigger:
                schedule: 5 3 * * *
      data:
        enabled: true
        path: /mnt/tank/data
        mountPath: /data
        server: ${TRUENAS_IP}
        type: nfs
      backup:
        enabled: true
        path: /mnt/tank/backup/apps/sonarr
        mountPath: /backup
        server: ${TRUENAS_IP}
        type: nfs
